### ISSUE TITLE
New feature: support sending to multiple devices at once

### ISSUE THREAD

**Issue by ktiniatros** [fcannizzaro/firebase-messaging#1]
Hi,

For personal use, I made a small update to be able to send to multiple devices at once, using the registration_ids parameter.

So, the first parameter [to] can either be a string for sending to one device or an array of strings to send to many devices.

Are you interested to merge this change to your codebase?

The possible merge request: https://github.com/fcannizzaro/firebase-messaging/compare/master...ktiniatros:dev?expand=1

**Comment by fcannizzaro** [comment]
#2 thanks :+1:
